version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
      - unzip terraform_1.9.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo Building Terraform infrastructure...
      - terraform init
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
