version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
      - unzip terraform_1.9.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo Preparing for Terraform operations...
      - aws --version
      - echo Retrieving GitHub token from AWS Secrets Manager...
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github_pat --query SecretString --output text | jq -r .github_token)

  build:
    commands:
      - echo Building Terraform infrastructure...
      - terraform init
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo Terraform build complete!
      - echo Configuring Git...
      - git config --global user.name 'KosariRajender'
      - git config --global user.email 'rajender.kosari01@gmail.com'
      - echo Cloning repository...
      - git clone https://github.com/KosariRajender/AWS-Devops-Project-1.git
      - cd AWS-Devops-Project-1
      - echo Downloading artifacts from S3...
      - aws s3 cp s3://codepipeline-us-east-1-360389744253.pipelines/pipeline/SourceArti/gBxbEzw . --recursive
      - echo Copying artifacts...
      - cp -r * /path/to/target/directory/  # Adjust this path based on where you want to place the artifacts
      - git add .
      - git commit -m 'Add build artifacts'
      - git push https://$GITHUB_TOKEN@github.com/KosariRajender/AWS-Devops-Project-1.git

artifacts:
  files:
    - '**/*'
