version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
      - unzip terraform_1.9.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo Preparing for Terraform operations...
      - aws --version

  build:
    commands:
      - echo Running Terraform plan...
      - terraform init
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Terraform plan complete!
      - echo Uploading plan to S3...
      - aws s3 cp tfplan s3://your-s3-bucket/terraform-plans/$(date +%Y-%m-%d-%H-%M-%S)-tfplan

artifacts:
  files:
    - '**/*'
