version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
      - unzip terraform_1.9.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
  pre_build:
    commands:
      - echo Preparing for Terraform operations...
      # Here you can run additional commands if needed, like installing AWS CLI
      - aws --version
  build:
    commands:
      - echo Building Terraform infrastructure...
      - terraform init
      - terraform plan -lock=false
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Terraform build complete!

artifacts:
  files:
    - '**/*'
