version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.9.4  # Specify your Terraform version
    commands:
      - echo "Installing Terraform"
      - curl -LO https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
      - unzip terraform_1.9.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Preparing Terraform"
  build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
      - echo "Applying Terraform"
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
